language: generic

matrix:
  include:
    - os: linux
      sudo: false
      env: CXX=g++-5
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5' ]
    - os: linux
      sudo: false
      env: CXX=clang++
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      sudo: required # required to workaround https://github.com/mapbox/node-cpp-skel/issues/93
      env: CXX=clang++ CXXFLAGS="-fsanitize=address,undefined -fno-sanitize-recover=all"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: osx
      osx_image: xcode8.3
    # clang-tidy specific job
    - os: linux
      sudo: false
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
      script:
        # First run the clang-tidy target
        # This target does not currently return non-zero when problems
        # are fixed, but rather it fixes automatically. Changed files
        # will be detected by the format target and will trigger an error
        - make tidy
        # Now we run the clang-format script. Any code formatting changes
        # will trigger the build to fail (idea here is to get us to pay attention
        # and get in the habit of running these locally before committing)
        - make format


env:
  global:
   - CMAKE_VERSION="3.8.2"

install:
  # set up the environment by installing mason and clang++
  - ./scripts/setup.sh --config local.env
  # put mason and clang++ on PATH
  - source local.env
  - mason install cmake ${CMAKE_VERSION}
  - mason link cmake ${CMAKE_VERSION}
  - which cmake

script:
  - make release
  - make test
  - make clean
  - make debug
  - make test
  - make clean
